services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - .data:/etc/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
