services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: biscoin-db
    networks: 
     - backend
    restart: always
    volumes:
      - .data:/etc/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  adminer:
    image: adminer 
    networks: 
     - backend
    restart: always
    ports:
      - 8089:8080
      #  backend:
      #   build: .
      #  networks:
      #  - backend
      #environment:
      # - DB_SERVER=biscoin-db
      #ports:
      # - 8000:8080
networks:
  backend:
    name: backend
