services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: marker-db
    networks: 
     - backend
    restart: always
    volumes:
      - .data:/etc/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  backend:
    build: .
    networks:
      - backend
    ports:
       - 8079:8080
networks:
  backend:
    name: backend
